app/routes/auth.py
import functools

from flask import(
    Blueprint, flash, g, redirect, render_template, request, session, url_for, abort
)

from werkzeug.security import check_password_hash, generate_password_hash

from app.db import get_db

bp = Blueprint('auth', __name__, url_prefix = '/auth')
# auth is the name of the blueprint
# __name__ is the location of the bp 


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required'
        elif not password:
            error = 'Password is required'
        # below part is confusing
        if error is None:
            try:
                if len(password) < 8:
                    flash('Password must be at least 8 characters long.', 'danger')
                    return redirect(url_for('auth.register'))  
                
                elif not any(char.isupper() for char in password):
                    flash('Password must contain at least one uppercase letter.', 'danger')
                    return redirect(url_for('auth.register'))
                
                elif not any(char.islower() for char in password):
                    flash('Password must contain at least one lowercase letter.', 'danger')
                    return redirect(url_for('auth.register'))
                
                elif not any(char.isdigit() for char in password):
                    flash('Password must contain at least one numeric digit.', 'danger')
                    return redirect(url_for('auth.register'))
                
                elif not any(char.isalnum() or char in '!@#$%^&*()-_=+[]{}|;:\'",.<>?/`~' for char in password):
                    flash('Password must contain at least one special character.', 'danger')
                    return redirect(url_for('auth.register'))


                db.execute("INSERT INTO user (username, password) VALUES(?, ?)",
                (username, generate_password_hash(password)),)
                db.commit()
            
                return redirect(url_for("auth.login"))   
             
            except db.IntegrityError:
                error = f"User {username} is already registered"
            
            
         # this part has a problem
        else:
            return redirect(url_for("auth.login"))
        
        flash(error)
    return render_template('auth/register.html')


@bp.route('/login', methods = ('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute('SELECT * FROM user WHERE username = ?', (username,)).fetchone()
        
        if user is None:
            error = 'Incorrect username'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password'

        if error is None:
            session.clear()         # clear any current session and assign a new one
            session['user_id'] = user['user_id']    # in the user table we have column user_id, that's what we are using
            return redirect(url_for('home'))
        
        flash(error)
    # below line is tricky to understand how it connects to the above code
    return render_template('auth/login.html')




@bp.route('/logout')
def logout():
    session.clear()
  
    return redirect(url_for('home'))


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE user_id = ?', (user_id,)
        ).fetchone()


# ensure users are logged in for some resources
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        
        return view(**kwargs)
    
    return wrapped_view  # recursive function here base case is a negation of the if stm


            

app/routes/help.py
from flask import(
    Blueprint, flash, g, redirect, render_template, request, url_for
)

from werkzeug.exceptions import abort

from app.routes.auth import login_required
from app.db import get_db
from app.routes.home import home

bp = Blueprint('help', __name__)

@bp.route('/help', methods=('GET', 'POST'))
@login_required
def platform():
    db = get_db()
    error = None
    try:
        if request.method == 'POST':
            required_fields = ['addiction-type', 'duration', 'cause', 'severity', 'age', 'gender']
            form_data = {field: request.form.get(field) for field in required_fields}
            data = list(form_data.values())

            if not all(form_data.values()):
                return "Please fill in all fields." 

            # get the logged in user's id
            username = g.user['username']
            logged_in_userid = db.execute("SELECT user_id FROM user WHERE username = ?", (username,)).fetchone()['user_id']
            
            # # now add the user_id to the list of data to be inserted into db
            data.append(logged_in_userid)

            # SAVE FORM DATA INTO DB
            stm = 'INSERT INTO addiction_data (addiction_type, duration, cause, severity, age, gender, user_id) VALUES(?, ?, ?, ?, ?, ?, ?)'
            db.execute(stm, data)
            db.commit()
        return render_template('help/platform.html')
    
    except db.IntegrityError:
        error = 'error!, cannot submit form twice.'
        flash(error)
        return redirect(url_for('home'))



@bp.route('/help/chat-doctor')
@login_required
def chat_doctor():
    return render_template('help/chat-doctor.html')


@bp.route('/help/peer-forum')
@login_required
def peer_forum():
    return render_template('help/peer-forum.html')


# educational_resources
# @bp.route('/help/eresources')
# @login_required
# def e_resources():
#     return render_template('help/educational_resources.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- bootstrap css, you can comment / uncomment to see effects -->
</head>
<body class="body">
    {% include "navigation.html" %}
   
    <section id="introduction">
        <div class="container">
            <h1 class="introduction">Welcome to Addiction Solver</h1>
            <p class="intro-message">Are you or someone you care about struggling with addiction? Welcome to Addiction Solver – a compassionate companion on the journey to recovery. Our app is designed to provide support, guidance, and personalized solutions to help you overcome addiction and build a healthier, more fulfilling life.</p>
        </div>
    </section>

    <section class="user-story">
        <div class="container text-center">
            <h2 class="text-success">Success Stories</h2>
            <!-- one row for all story display -->
            <div class="row d-flex flex-nowrap grid gap-3 " style="width: 500vw;">
                {% for story in stories %}                    
                    <div class="col success" id="story" style="min-width: 25vw; max-width: 25vw;">
                        <a href="{{ story[2] }}" id="mylink">
                            <div class="name">
                                <h4 class="dark" id="dark">{{ story[0] }}</h4>
                            </div>
                            {{ story[1] }}
                        </a>
                    </div>
                {%endfor%}              
            </div>
        </div>
    </section>    
          <!-- Addiction Information Form -->
    <section id="addiction-form-section">
       <h3>Tell Us About Your Addiction</h3>
       <form action=" {{ url_for('help') }} " method="POST" id="addiction-form">
          <label for="addiction-type">Type of Addiction:</label>
          <input type="text" id="addiction-type" name="addiction-type" required>

          <label for="duration">Time Duration of Addiction (in months):</label>
          <input type="number" id="duration" name="duration" required>

          <label for="cause">Possible Cause of Addiction:</label>
          <textarea id="cause" name="cause" rows="4" required></textarea>

          <label for="severity">Severity of Addiction:</label>
          <select id="severity" name="severity" required>
            <option value="blank"></option>
             <option value="mild">Mild</option>
             <option value="moderate">Moderate</option>
             <option value="severe">Severe</option>
          </select>

          <label for="age">Age:</label>
          <input type="number" id="age" name="age" required>

          <label for="gender">Gender:</label>
          <select id="gender" name="gender" required>
            <option value="blank"></option>
             <option value="male">Male</option>
             <option value="female">Female</option>
             <option value="other">Other</option>
          </select>

          <button type="submit">Submit</button>
       </form>
    </section>
    

    
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <!-- bootstrap js, you can comment / uncomment to see effects -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/templates/error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/error_page.css') }}">
</head>
<body>
    <header>
        <h1>Error Occurred</h1>
    </header>
    <main>
        <section>
            <p>Oops! Something went wrong.</p>
            <p>Please go back or try again later.</p>
        </section>
    </main>

    <a href="/show_games/<username>">Go Home</a>
    <br>
    <footer>
        <p>&copy; 2023 Games Lounge</p>
    </footer>
</body>
</html>

app/templates/navigation.html
<!DOCTYPE html>

<section id="navbar-1">
    <nav class="navbar fixed-top navbar-expand-sm bg-body-tertiary test">
        <div class="container-fluid">
            <div class="system-title">
                <span class="navbar-brand mb-0 h1">Addiction Solver</span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 customize">
                    {% if g.user %}
                        <!-- only for logged in user -->
                        <!-- user name -->
                        
                        <!-- help -->
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('help.platform') }}">Help</a>
                        </li>                        
                
                        <!-- logout -->
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                        
                        <li style="margin-left: 200px; margin-top: 7px; font-size: 20px; font-weight: bolder;">{{ g.user['username'].upper() }}</li>
                    {% else %}
                        <!-- show this for non logged in user -->
                        <!-- home -->


                        <!-- register -->
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>

                        <!-- login -->
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                    {% endif %}
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li> -->
                </ul>
            </div>
        </div>
    </nav>

</section>

app/templates/shared.html
<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png')}}" type="image/x-icon">